services:
  meilisearch:
    image: "docker.io/getmeili/meilisearch:v1.7"
    environment:
      MEILI_MASTER_KEY: ${MELLISEARCH_KEY:-r2Lr7e68Yf3y-GekSB7pz6IWNpg0G-lFpJYTG4VUqB4}
    volumes:
      - "meilisearch-data:/meili_data"

  web:
    build: .
    ports:
      - "80:8000"
    volumes:
      - "sqlite-data:/app/database/sqlite"
    environment:
      MEILI_HOST: "http://meilisearch:7700"
      MEILI_MASTER_KEY: ${MELLISEARCH_KEY:-r2Lr7e68Yf3y-GekSB7pz6IWNpg0G-lFpJYTG4VUqB4}
      EVENTFULLY_JWT_KEY: "<secret key for generating JWT tokens, put a secure random string here>"
      EVENTFULLY_ANALYTICS_URL: "<url to an analytics service (optional)>"
      EVENTFULLY_LEGAL_NOTICE: "<legal notice text, use \n for line breaks (optional)>"
    depends_on:
      - "meilisearch"

volumes:
  meilisearch-data:
  sqlite-data:
